<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ $headline }} · MYinboxLAB</title>
    <link rel="preconnect" href="https://fonts.bunny.net"><link href="https://fonts.bunny.net/css?family=bricolage-grotesque:500,600,700,800|dm-sans:400,500,600,700&display=swap" rel="stylesheet">
    @vite(['resources/css/app.css','resources/js/app.js'])
    <style>
        :root{--cream:#fffaf0;--ink:#111214;--line:#d8d4ca;--channel:{{ $accent }}}*{box-sizing:border-box}body{margin:0;background:var(--cream);color:var(--ink);font-family:'DM Sans',sans-serif}.wrap{width:calc(100% - 96px);margin:auto}.page h1,.page h2,.page .brand{font-family:'Bricolage Grotesque',sans-serif;letter-spacing:-.07em}.nav{position:absolute;z-index:2;inset:0 0 auto;height:94px;display:flex;align-items:center;justify-content:space-between;color:#fff}.brand{font-size:1.55rem;font-weight:800}.nav nav{display:flex;gap:32px;align-items:center}.nav a{color:inherit;text-decoration:none}.nav-cta{padding:14px 24px;border:1px solid currentColor;border-radius:999px}.hero{min-height:100svh;display:flex;align-items:center;background:linear-gradient(90deg,rgba(0,0,0,.82),rgba(0,0,0,.18)),url('{{ asset('images/marketing/instagram-hero.png') }}') center/cover;color:#fff}.copy{max-width:900px;padding-top:80px}.eyebrow{margin-bottom:22px;color:var(--channel);font-size:.75rem;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.copy h1{max-width:900px;margin:0 0 24px;font-size:clamp(4rem,8vw,8.5rem);line-height:.82}.copy p{max-width:600px;margin:0 0 36px;font-size:1.2rem;line-height:1.5}.button{display:inline-flex;padding:16px 25px;border-radius:999px;background:var(--channel);color:#fff;text-decoration:none;font-weight:800}.section{padding:150px 0}.section h2{max-width:850px;margin:0 0 22px;font-size:clamp(3.5rem,6vw,6.5rem);line-height:.84}.section p{max-width:620px;font-size:1.1rem;line-height:1.6;color:#62636a}.faq{border-top:4px solid var(--channel)}.faq details{border-bottom:1px solid var(--line);padding:25px 0}.faq summary{cursor:pointer;font-size:1.2rem;font-weight:700}.faq p{margin:18px 0 0}.footer{padding:38px 0;background:#050505;color:#fff}.footer a{color:#fff;text-decoration:none}@media(max-width:720px){.wrap{width:calc(100% - 44px)}.nav{height:78px}.nav nav a:not(.nav-cta){display:none}.hero{align-items:flex-start;background-position:62% center}.copy{padding-top:150px}.copy h1{font-size:clamp(3.1rem,14vw,4.4rem)}.copy p{font-size:1rem}.section{padding:88px 0}}
    </style>
</head>
<body class="page"><header class="nav wrap"><a class="brand" href="{{ route('landing') }}">MYinboxLAB</a><nav><a href="#how">How it works</a><a href="#faq">FAQ</a><a class="nav-cta" href="{{ auth()->check()?route('dashboard'):route('register') }}">Get started</a></nav></header><main><section class="hero"><div class="wrap"><div class="copy"><div class="eyebrow">{{ $eyebrow }}</div><h1>{{ $headline }}</h1><p>{{ $body }}</p><a class="button" href="{{ auth()->check()?route('dashboard'):route('register') }}">{{ $cta }}</a></div></div></section><section class="section" id="how"><div class="wrap"><h2>{{ $channel }} conversations, made useful.</h2><p>MYinboxLAB keeps customer messages organised, gives your team the context to respond well, and makes it easier to turn interest into action.</p></div></section><section class="section faq" id="faq"><div class="wrap"><h2>{{ $channel }} questions, answered.</h2><details><summary>Can my team manage {{ $channel }} messages here?</summary><p>Yes. Conversations stay in one shared inbox so your team can respond and take over when needed.</p></details><details><summary>Can we control how replies sound?</summary><p>Set your services, policies, tone, and escalation guidance in your workspace.</p></details></div></section></main><footer class="footer"><div class="wrap"><a class="brand" href="{{ route('landing') }}">MYinboxLAB</a></div></footer></body>
</html>
